# A Docker Compose must always start with the version tag.
# We use '3' because it's the last version.
version: '3'

# You should know that Docker Compose works with services.
# 1 service = 1 container.
# For example, a service, a server, a client, a database...
# We use the keyword 'services' to start to create services.
services:
  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:latest'

    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    ports:
      - 5438:5432

    environment:
      POSTGRES_USER: fmoyses # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: 1234 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: tpldb # The PostgreSQL default database (automatically created at first launch)
    volumes:
      #- ./sql-scripts:/docker-entrypoint-initdb.d
      - ./sql-scripts/create.sql:/docker-entrypoint-initdb.d/create.sql
